import type { Critique, Deck } from "./types";

export const DEMO_DESCRIPTION =
  "FarmAI is an AI-powered agriculture platform that helps small farmers make better irrigation and crop-management decisions using satellite imagery, weather information and machine learning. Farmers receive simple recommendations through a mobile application.";

export const FARMAI_DECK: Deck = {
  startupName: "FarmAI",
  tagline: "Decision intelligence for the world's small farms.",
  industry: "AI + Agriculture",
  oneLiner:
    "FarmAI turns satellite imagery, weather data and machine learning into simple daily irrigation and crop decisions for small farmers, delivered through a mobile app.",
  slides: [
    {
      number: 1,
      title: "FarmAI",
      purpose: "Cover — set the tone and the one-liner.",
      content: [
        "Decision intelligence for the world's small farms.",
        "Satellite imagery + weather + machine learning → simple daily recommendations.",
        "Delivered through a mobile app built for low-connectivity environments.",
      ],
      keyMetric: "",
      assumptions: [],
      missingInformation: ["Founder name(s) and contact details for the cover."],
    },
    {
      number: 2,
      title: "Small farmers make high-stakes decisions with almost no data",
      purpose: "Make the problem specific, human and expensive.",
      content: [
        "Irrigation and crop-management decisions are made on instinct, tradition or neighbours' advice.",
        "Over- or under-watering wastes water, raises input costs and reduces yield.",
        "Weather volatility is increasing, making past experience a weaker guide each season.",
        "Existing precision-agriculture tools are built and priced for large, mechanised farms.",
      ],
      keyMetric: "AI ESTIMATE — VALIDATE BEFORE PRESENTING: ~500M smallholder farms worldwide (FAO-type figure; confirm source)",
      assumptions: ["Small farmers are willing to change irrigation behaviour when given clear guidance."],
      missingInformation: ["Quantified yield or water loss from poor irrigation in your target region.", "Founder interviews or field observations that confirm the pain."],
    },
    {
      number: 3,
      title: "A daily 'what to do today' for every field",
      purpose: "Show the solution simply — outcome first, technology second.",
      content: [
        "Farmers register their fields once; FarmAI monitors them from satellite and weather feeds.",
        "Machine learning converts raw signals into plain-language actions: irrigate / hold / scout for stress.",
        "Recommendations arrive as short mobile notifications in the farmer's language.",
        "No sensors or hardware required to get started.",
      ],
      keyMetric: "Zero-hardware onboarding (founder-described design goal)",
      assumptions: ["Free satellite data resolution is sufficient for small plot sizes."],
      missingInformation: ["Evidence that recommendation accuracy is good enough to trust in the field."],
    },
    {
      number: 4,
      title: "A large, underserved market",
      purpose: "Size the opportunity with transparent methodology.",
      content: [
        "AI ESTIMATE — VALIDATE BEFORE PRESENTING: Global smallholder farms ≈ 500M, farming ~12% of agricultural land.",
        "Methodology: TAM = addressable smallholder farms × achievable annual software spend per farm.",
        "AI ESTIMATE: at $20–40/farm/year, a 5% reachable segment implies a $0.5–1B serviceable opportunity.",
        "Initial wedge: one region with high smartphone penetration and water-stressed irrigation.",
      ],
      keyMetric: "AI ESTIMATE — VALIDATE BEFORE PRESENTING: $0.5–1B SAM",
      assumptions: ["Smallholders (or their buyers/cooperatives) can pay $20–40 per year.", "Smartphone penetration in the launch region exceeds 60%."],
      missingInformation: ["Chosen launch country/region.", "Bottom-up numbers: farms in region × willingness to pay from surveys."],
    },
    {
      number: 5,
      title: "How FarmAI works",
      purpose: "Explain the product flow in four steps.",
      content: [
        "1. Map — farmer draws field boundaries in the app (or an agent does it for them).",
        "2. Sense — daily satellite vegetation indices + local weather forecasts are ingested.",
        "3. Reason — ML models estimate crop water stress and disease risk per field.",
        "4. Recommend — a single clear action is pushed each morning; feedback loop improves models.",
      ],
      keyMetric: "One action per field per day (product principle)",
      assumptions: ["Farmers can accurately map field boundaries in the app."],
      missingInformation: ["Current product status: prototype, pilot or production?"],
    },
    {
      number: 6,
      title: "Business model",
      purpose: "Show how the company makes money and who pays.",
      content: [
        "Primary: low-cost annual subscription per farm, paid by farmers or via cooperatives.",
        "B2B2C channel: agri-input suppliers, cooperatives and lenders sponsor subscriptions for their farmer networks.",
        "Upsell: aggregated, anonymised field-health analytics for insurers and buyers.",
        "BUSINESS MODEL NOT SPECIFIED BY FOUNDER — the above is a recommended structure to validate.",
      ],
      keyMetric: "AI ESTIMATE: $20–40 per farm per year",
      assumptions: ["Cooperatives are willing to pay on behalf of farmers.", "Analytics upsell is acceptable under data-privacy expectations."],
      missingInformation: ["Which party actually pays first.", "Unit economics: acquisition cost per farm vs. annual revenue."],
    },
    {
      number: 7,
      title: "Competition & differentiation",
      purpose: "Show awareness of alternatives and why FarmAI wins.",
      content: [
        "Status quo: intuition, extension officers, WhatsApp groups.",
        "Precision-ag platforms (e.g. sensor-based, enterprise-priced) target large farms.",
        "Weather apps give information, not decisions.",
        "FarmAI: hardware-free, decision-first, priced for smallholders, local-language delivery.",
      ],
      keyMetric: "",
      assumptions: ["Hardware-free approach retains enough accuracy to be a real advantage."],
      missingInformation: ["Named competitors in the launch region.", "Defensibility: proprietary data, distribution partnerships or model performance."],
    },
    {
      number: 8,
      title: "Go-to-market",
      purpose: "Explain how the first customers are acquired.",
      content: [
        "Land: partner with 2–3 farmer cooperatives in one water-stressed region for a paid pilot.",
        "Expand: cooperative field agents onboard farmers; referral incentives for neighbours.",
        "Distribute: bundle with agri-input suppliers and micro-lenders who benefit from higher yields.",
        "Retain: seasonal proof — show water saved and yield delta at harvest.",
      ],
      keyMetric: "",
      assumptions: ["Cooperatives are reachable and motivated to run pilots."],
      missingInformation: ["Named pilot partners or letters of intent.", "Customer acquisition cost assumptions."],
    },
    {
      number: 9,
      title: "Traction & validation",
      purpose: "Honest status of evidence.",
      content: [
        "TRACTION NOT PROVIDED — the founder has not shared users, pilots, revenue or partnerships.",
        "Evidence to collect before pitching: number of farmer interviews and key insights.",
        "Evidence to collect: a pilot with ≥50 fields and measured recommendation accuracy.",
        "Evidence to collect: signed letters of intent from cooperatives or input suppliers.",
      ],
      keyMetric: "TRACTION NOT PROVIDED",
      assumptions: [],
      missingInformation: ["Any pilot, waitlist, revenue, partnership or field-test data."],
    },
    {
      number: 10,
      title: "Financials & funding ask",
      purpose: "Show the use of funds and the milestones it buys.",
      content: [
        "FUNDING ASK NOT PROVIDED — structure below is a recommendation for the founder to complete.",
        "Use of funds (suggested split): 45% product & ML, 35% field operations & partnerships, 20% G&A.",
        "AI ESTIMATE: 18-month runway to reach a 5,000-farm paid pilot and first cooperative contracts.",
        "Key financial assumptions must be stated: price per farm, gross margin, churn, CAC.",
      ],
      keyMetric: "FUNDING ASK NOT PROVIDED",
      assumptions: ["Costs are dominated by team and field operations rather than data acquisition."],
      missingInformation: ["Round size, valuation expectations and 18-month milestones.", "Revenue model inputs for a simple projection."],
    },
    {
      number: 11,
      title: "Team & vision",
      purpose: "Why this team, and where this goes.",
      content: [
        "TEAM DETAILS NOT PROVIDED — add founders, relevant agri/ML/distribution experience and advisors.",
        "Vision: become the default decision layer for the 500M small farms that feed most of the world.",
        "Long-term: field-level data becomes the foundation for credit, insurance and supply-chain products.",
      ],
      keyMetric: "",
      assumptions: [],
      missingInformation: ["Founder backgrounds and why they are uniquely positioned."],
    },
  ],
};

export const FARMAI_CRITIQUE: Critique = {
  overallSummary:
    "FarmAI has a clear, human problem and a credible hardware-free wedge, but the deck currently rests on estimates rather than evidence. A seed investor will focus on three gaps: who actually pays, whether recommendations are accurate enough to be trusted, and any signal that farmers or cooperatives want this today.",
  issues: [
    {
      id: "farmai-1",
      slideNumber: 9,
      category: "Validation",
      severity: "critical",
      title: "No traction or field evidence",
      feedback: "Slide 9 openly states that no users, pilots or partnerships exist. Investors will read the rest of the deck as hypothesis.",
      whyItMatters: "At seed stage, even 20 farmer interviews or one small pilot dramatically changes credibility. Without it the market and model slides cannot be trusted.",
      suggestion: "Run a 4–6 week pilot with one cooperative (≥50 fields). Report recommendation accuracy, farmer follow-through rate and any water or yield delta.",
    },
    {
      id: "farmai-2",
      slideNumber: 6,
      category: "Business Model",
      severity: "critical",
      title: "Unclear who pays",
      feedback: "The business model lists three possible payers (farmers, cooperatives, insurers) without committing to one. That reads as untested.",
      whyItMatters: "Smallholder willingness to pay is historically low; the payer determines your sales motion, pricing and CAC.",
      suggestion: "Pick the first payer explicitly (e.g. cooperatives sponsoring farmers) and show one line of evidence — a quote, LOI or pilot pricing conversation.",
    },
    {
      id: "farmai-3",
      slideNumber: 4,
      category: "Market Size",
      severity: "warning",
      title: "Top-down TAM with untested price point",
      feedback: "The $0.5–1B figure depends on a $20–40/farm/year assumption and a 5% reachability figure, neither of which is sourced.",
      whyItMatters: "Investors will ask 'how did you calculate that?' — a top-down estimate with unverified inputs invites a challenge you cannot yet answer.",
      suggestion: "Rebuild the market slide bottom-up for the launch region: number of farms × verified price × realistic 3-year penetration. Label the global number as context only.",
    },
    {
      id: "farmai-4",
      slideNumber: 7,
      category: "Differentiation",
      severity: "warning",
      title: "Defensibility is not explained",
      feedback: "Hardware-free and low-priced describes positioning, not a moat. Satellite and weather data are available to any competitor.",
      whyItMatters: "A well-funded agri-tech player could replicate the feature set; investors want to know what compounds over time.",
      suggestion: "Articulate the data flywheel: farmer feedback on recommendations creates labelled ground-truth that improves models and is hard to copy. Name two regional competitors and contrast directly.",
    },
    {
      id: "farmai-5",
      slideNumber: 3,
      category: "Product Risk",
      severity: "warning",
      title: "Recommendation accuracy is unproven",
      feedback: "The solution assumes free satellite resolution is enough for small plots, but this is listed as an assumption with no supporting result.",
      whyItMatters: "If a farmer follows a wrong irrigation recommendation once, trust is lost. Accuracy is the product.",
      suggestion: "Add a slide-level metric: model accuracy vs. ground truth from your pilot fields, and the minimum plot size you support.",
    },
    {
      id: "farmai-6",
      slideNumber: 10,
      category: "Funding Logic",
      severity: "info",
      title: "Funding ask and milestones are missing",
      feedback: "The financial slide has a suggested use-of-funds split but no round size, runway or milestone plan.",
      whyItMatters: "Investors need to know what this money buys and what the next round will be raised on.",
      suggestion: "State the ask (e.g. $750k pre-seed), 18-month milestones (pilot → paid cooperatives → X farms), and the three assumptions that drive the model.",
    },
    {
      id: "farmai-7",
      slideNumber: 11,
      category: "Team",
      severity: "info",
      title: "Team slide is empty",
      feedback: "No founder backgrounds are provided, so founder–market fit cannot be assessed.",
      whyItMatters: "For a pre-traction company, the team is the primary asset investors underwrite.",
      suggestion: "Add each founder's relevant experience in agriculture, ML or rural distribution, plus any advisors with cooperative or agronomy credibility.",
    },
  ],
  investorQuestions: [
    "Where will your first 100 paying farms come from, and who signs the cheque?",
    "How did you calculate the $0.5–1B serviceable market?",
    "What is the accuracy of your irrigation recommendations against ground truth?",
    "What makes this difficult for an established agri-input company to copy?",
    "What evidence suggests smallholders or cooperatives will pay $20–40 a year?",
    "What happens to farmer trust after the first wrong recommendation?",
  ],
  pitchHealth: [
    { dimension: "Problem Clarity", status: "Strong", note: "Specific, human and tied to cost and yield." },
    { dimension: "Market Evidence", status: "Needs Evidence", note: "Top-down estimate with unverified price and penetration inputs." },
    { dimension: "Differentiation", status: "Needs Work", note: "Positioning stated, moat not." },
    { dimension: "Business Model", status: "Clear", note: "Structure is understandable but the first payer is undecided." },
    { dimension: "Traction Evidence", status: "Missing", note: "No pilots, users or partners provided." },
    { dimension: "Financial Assumptions", status: "Needs Validation", note: "No round size or milestone plan." },
  ],
};
